import { z } from 'zod';

/** A hex color, e.g. "#1a2b3c". */
export const Hex = z.string().regex(/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/, 'must be a hex color');

/**
 * Per-site design tokens. Generated by the Theme-Designer agent and rendered to
 * CSS variables by @simplesight/theme. This is the entire visual identity of a
 * site expressed as data — no per-site CSS files.
 */
export const ThemeTokens = z.object({
  palette: z.object({
    background: Hex,
    foreground: Hex,
    primary: Hex,
    primaryForeground: Hex,
    accent: Hex,
    muted: Hex,
    mutedForeground: Hex,
    border: Hex,
    card: Hex,
    cardForeground: Hex,
  }),
  typography: z.object({
    headingFamily: z.string(), // CSS font-family stack
    bodyFamily: z.string(),
    baseSizePx: z.number().min(14).max(20),
    scaleRatio: z.number().min(1.1).max(1.5), // modular type scale
    headingWeight: z.number().min(400).max(900),
    bodyWeight: z.number().min(300).max(600),
  }),
  spacing: z.object({
    unitPx: z.number().min(2).max(12), // base spacing unit
    sectionPaddingY: z.number().min(32).max(160), // vertical rhythm between sections
    contentMaxWidthPx: z.number().min(960).max(1440),
  }),
  radius: z.object({
    smPx: z.number().min(0).max(12),
    mdPx: z.number().min(0).max(24),
    lgPx: z.number().min(0).max(40),
  }),
  /** Overall visual character — drives subtle block styling choices. */
  density: z.enum(['airy', 'comfortable', 'compact']),
  mood: z.enum(['minimal', 'warm', 'bold', 'classic', 'modern', 'playful']),
});
export type ThemeTokens = z.infer<typeof ThemeTokens>;
