import { generateJson } from '@simplesight/engine';
import { getSkill } from '@simplesight/skills';
import { z } from 'zod';
import { fontWhitelistForPrompt } from './fonts';

/**
 * The committed art direction for ONE bespoke site — the artifact that makes
 * every site distinct (unlike the template approach, where design was fixed).
 * Generated by Opus from the onboarding Q&A + the design skills.
 */
export const DesignBriefSchema = z.object({
  direction: z.string().describe('one distinctive aesthetic direction, e.g. "warm editorial minimalism" or "clinical brutalist"'),
  rationale: z.string().describe('why this direction fits the business + audience'),
  palette: z.object({
    mode: z.enum(['light', 'dark']),
    background: z.string(),
    foreground: z.string(),
    primary: z.string(),
    accent: z.string(),
    muted: z.string(),
    note: z.string().describe('OKLCH reasoning; banned defaults avoided'),
  }),
  fonts: z.object({
    display: z.string().describe('a real, non-default variable font for headings'),
    body: z.string(),
    pairingNote: z.string(),
  }),
  type: z.object({ displayTreatment: z.string(), scaleNote: z.string() }),
  spacing: z.object({ density: z.enum(['airy', 'comfortable', 'compact']), rhythmNote: z.string() }),
  motion: z.object({ level: z.enum(['subtle', 'expressive']), note: z.string() }),
  signatureDevices: z.array(z.string()).min(3).describe('3-5 specific visual devices unique to this site'),
  imagery: z.object({ direction: z.string(), treatment: z.string() }),
  voice: z.string(),
  pages: z
    .array(
      z.object({
        name: z.string(),
        slug: z.string(),
        sections: z.array(z.object({ kind: z.string(), intent: z.string() })).min(3),
      }),
    )
    .min(3)
    .describe('sitemap with a per-page section narrative (described compositions, not fixed blocks)'),
});
export type DesignBrief = z.infer<typeof DesignBriefSchema>;

function skillText(...names: string[]): string {
  return names
    .map((n) => getSkill(n))
    .filter(Boolean)
    .map((s) => `## ${s!.name}\n${s!.body}`)
    .join('\n\n');
}

/**
 * Generate a committed Design Brief from a business prompt / onboarding answers.
 * The brief is deliberately distinctive — the anti-generic lever.
 */
export async function generateDesignBrief(
  businessPrompt: string,
  model: string,
  onCost?: (cents: number) => void,
): Promise<DesignBrief> {
  const system = `You are an award-winning art director scoping a BESPOKE website. Your job is to commit to ONE distinctive, specific aesthetic direction that fits this exact business — never the safe, generic average. Two different businesses must yield two visibly different briefs.

Apply this expertise:
${skillText('premium-design', 'design-standards', 'marketing-voice')}

Hard rules:
- Name the category cliché first, then deliberately avoid or subvert it. (climbing gym → chalky earth tones; dentist → clinical sky-blue; law firm → navy + gold serif; wellness → sage + cream; SaaS → blue-on-white with a gradient blob. If your instinct is the cliché, change it.)
- Commit to one clear direction and justify it. Avoid the default SaaS look.
- Specify a grid system and ONE signature section unique to this business (a composition no competitor would have).
- Palette in OKLCH thinking, tinted neutrals, never pure gray/black, never the default blue-on-white. WCAG AA.
- Fonts: choose ONLY from this whitelist (these are guaranteed available on Google Fonts). Name them EXACTLY as written. Pick a distinctive DISPLAY face + a readable BODY face (+ the accent serif handles one italic clause per headline; mono handles kickers):
${fontWhitelistForPrompt()}
- signatureDevices must be 3-5 SPECIFIC, buildable devices (e.g. "asymmetric 8/4 hero with a bordered stat rail", "OKLCH aurora-mesh hero", "hairline-bento metrics", "oversized serif section numerals", "duotone-treated photography").
- pages: a real sitemap (Home + the most common pages for this business) where each section has a clear intent — described as compositions, not generic block names.
- Voice per marketing-voice: human, specific, no AI-tell filler.`;

  const shape = `JSON shape (fill every field):
{
  "direction": string, "rationale": string,
  "palette": { "mode": "light"|"dark", "background": hex, "foreground": hex, "primary": hex, "accent": hex, "muted": hex, "note": string },
  "fonts": { "display": string, "body": string, "pairingNote": string },
  "type": { "displayTreatment": string, "scaleNote": string },
  "spacing": { "density": "airy"|"comfortable"|"compact", "rhythmNote": string },
  "motion": { "level": "subtle"|"expressive", "note": string },
  "signatureDevices": string[] (3-5),
  "imagery": { "direction": string, "treatment": string },
  "voice": string,
  "pages": [ { "name": string, "slug": string, "sections": [ { "kind": string, "intent": string } ] } ] (>=3 pages, >=3 sections each)
}`;
  return generateJson({
    model,
    schema: DesignBriefSchema,
    system,
    prompt: `Business / brief:\n${businessPrompt}\n\n${shape}\n\nProduce the Design Brief now as a single JSON object.`,
    maxOutputTokens: 6000,
    onCost,
  });
}
